experiment:
  variant: r50
  run_name: detr_r50_belt_batch_4
  save_dir: C:\Users\memorista\Desktop\Implementation-of-Object-Recognition-Algorithms-for-Conveyor-Belt-Defect-Detection\DETR\runs\r50\train\detr_r50_belt_batch_4
  device: cuda
  use_coco128: false
training:
  epochs: 300
  batch_size: 4
  lr: 0.0001
  lr_backbone: 1.0e-05
  lr_drop_epochs:
  - 150
  - 250
  lr_gamma: 0.1
  weight_decay: 0.0001
  clip_max_norm: 0.1
architecture:
  hidden_dim: 256
  nheads: 8
  enc_layers: 6
  dec_layers: 6
  dim_feedforward: 2048
  dropout: 0.1
  num_queries: 100
  position_embedding: sine
  pre_norm: false
  description: DETR base con backbone ResNet-50.
  backbone: resnet50
  dilation: false
  bbox_loss_coef: 5.0
  giou_loss_coef: 2.0
  eos_coef: 0.1
  aux_loss: true
  lr_backbone: 1.0e-05
  set_cost_class: 1.0
  set_cost_bbox: 5.0
  set_cost_giou: 2.0
  frozen_weights: null
  masks: false
  dataset_file: coco
  device: cuda
hardware_policy:
  bn2gn_policy: 'on'
  empty_cache_freq: 1
  use_amp: true
