experiment:
  variant: r50_4scale
  run_name: dino_r50_4s_belt
  save_dir: C:\Users\memorista\Implementation-of-Object-Detection-for-Conveyor-Belt-Defect-Detection\DINO\runs\r50_4scale\train\dino_r50_4s_belt
  device: cuda
  use_coco128: false
training:
  epochs: 300
  batch_size: 4
  lr: 0.0001
  lr_backbone: 1.0e-05
  lr_drop_epochs:
  - 150
  - 250
  lr_gamma: 0.1
  weight_decay: 0.0001
  clip_max_norm: 0.1
  ema_decay: 0.9997
architecture:
  query_dim: 4
  unic_layers: 0
  decoder_layer_noise: false
  dln_xy_noise: 0.2
  dln_hw_noise: 0.2
  add_channel_attention: false
  add_pos_value: false
  random_refpoints_xy: false
  two_stage_type: standard
  two_stage_pat_embed: 0
  two_stage_add_query_num: 0
  two_stage_learn_wh: false
  two_stage_keep_all_tokens: false
  dec_layer_number: null
  decoder_sa_type: sa
  decoder_module_seq:
  - sa
  - ca
  - ffn
  embed_init_tgt: true
  use_detached_boxes_dec_out: false
  transformer_activation: relu
  num_patterns: 0
  dec_pred_class_embed_share: true
  dec_pred_bbox_embed_share: true
  two_stage_bbox_embed_share: false
  two_stage_class_embed_share: false
  use_deformable_box_attn: false
  box_attn_type: roi_align
  match_unstable_error: true
  fix_refpoints_hw: -1
  use_dn: true
  dn_number: 100
  dn_box_noise_scale: 0.4
  dn_label_noise_ratio: 0.5
  matcher_type: HungarianMatcher
  num_select: 300
  nms_iou_threshold: -1
  interm_loss_coef: 1.0
  no_interm_box_loss: false
  pe_temperatureH: 20
  pe_temperatureW: 20
  backbone_freeze_keywords: null
  hidden_dim: 256
  nheads: 8
  enc_layers: 6
  dec_layers: 6
  dim_feedforward: 2048
  dropout: 0.0
  num_queries: 900
  position_embedding: sine
  pre_norm: false
  enc_n_points: 4
  dec_n_points: 4
  description: "DINO base con backbone ResNet-50 y 4 escalas de caracter\xEDsticas."
  backbone: resnet50
  dilation: false
  num_feature_levels: 4
  return_interm_indices:
  - 1
  - 2
  - 3
  bbox_loss_coef: 5.0
  giou_loss_coef: 2.0
  cls_loss_coef: 1.0
  focal_alpha: 0.25
  aux_loss: true
  lr_backbone: 1.0e-05
  set_cost_class: 2.0
  set_cost_bbox: 5.0
  set_cost_giou: 2.0
  frozen_weights: null
  masks: false
  dataset_file: coco
  device: cuda
  num_classes: 5
  dn_labelbook_size: 5
hardware_policy:
  bn2gn_policy: 'on'
  empty_cache_freq: 1
  use_amp: true
