# ==============================================================
# Departamento de Ingeniería Mecánica - Universidad de Chile
# Trabajo de Memoria de Título:
# "Implementación de algoritmos de reconocimiento de objetos
#  para la identificación de fallas en correas transportadoras"
# Autor: Fernando N.
# --------------------------------------------------------------
# Archivo: DINO/configs/dataset.yaml
# Descripción: Definición de rutas y clases para el dataset de fallas.
# ==============================================================

path: "../Dataset"

train: "train/images"
val:   "valid/images"
test:  "test/images"

nc: 5
names:
  0: Hole
  1: Impact Damage
  2: Puncture
  3: Tear
  4: Wear