# ==============================================================
# Departamento de Ingeniería Mecánica - Universidad de Chile
# Trabajo de Memoria de Título:
# "Implementación de algoritmos de reconocimiento de objetos
#  para la identificación de fallas en correas transportadoras"
# Autor: Fernando N.
# --------------------------------------------------------------
# Archivo: dataset.yaml
# Configuración del dataset utilizado por el modelo YOLOv11.
# Define rutas, número de clases y nombres de defectos detectados.
# ==============================================================

path: C:\Users\memorista\Desktop\Implementation-of-Object-Recognition-Algorithms-for-Conveyor-Belt-Defect-Detection\Dataset

train: images/train
val: images/val
test: images/test

nc: 5
names:
  0: Hole
  1: Impact Damage
  2: Puncture
  3: Tear
  4: Wear

download: false
format: yolo
imgsz: 640
