# model_variants.yaml
# Control de escalado de modelos YOLOv11

variants:
  n:  {depth_multiple: 0.50, width_multiple: 0.25, max_channels: 1024}
  s:  {depth_multiple: 0.50, width_multiple: 0.50, max_channels: 1024}
  m:  {depth_multiple: 0.50, width_multiple: 1.00, max_channels: 512}
  l:  {depth_multiple: 1.00, width_multiple: 1.00, max_channels: 512}
  xl: {depth_multiple: 1.00, width_multiple: 1.50, max_channels: 512}
