# ==============================================================
# Departamento de Ingeniería Mecánica - Universidad de Chile
# Trabajo de Memoria de Título:
# "Implementación de algoritmos de reconocimiento de objetos
#  para la identificación de fallas en correas transportadoras"
# Autor: Fernando N.
# --------------------------------------------------------------
# Archivo: train.yaml
# Configuración de entrenamiento YOLOv11 (Clasificación)
# ==============================================================

# ------------------------------
# CONFIGURACIÓN GENERAL
# ------------------------------
model: configs/yolo11.yaml
data: YOLOv11/configs/dataset.yaml
model_variant: n
task: classify           # 'detect' o 'classify'

# ------------------------------
# PARÁMETROS DE ENTRENAMIENTO
# ------------------------------
epochs: 100
batch_size: 8
imgsz: 640
num_workers: 4
gpu_memory_fraction: 0.8
seed: 42
deterministic: false
resume: true

# ------------------------------
# OPTIMIZADOR Y SCHEDULER
# ------------------------------
optimizer:
  name: AdamW
  lr: 0.002
  weight_decay: 0.0005
  momentum: 0.937

scheduler: cosine
lrf: 0.01

# ------------------------------
# EARLY STOPPING / CHECKPOINTS
# ------------------------------
early_stop_patience: 50
early_stop_min_delta: 1e-4
save_period: 1

# ------------------------------
# PARÁMETROS DEL LOADER
# ------------------------------
cache_images: false
accumulate: 1
grad_clip: 10.0
amp: true
